# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='routing.proto',
  package='routing',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rrouting.proto\x12\x07routing\")\n\x05Route\x12\x10\n\x08next_hop\x18\x01 \x01(\x03\x12\x0e\n\x06metric\x18\x02 \x01(\x01\"|\n\nRouteTable\x12/\n\x06routes\x18\x01 \x03(\x0b\x32\x1f.routing.RouteTable.RoutesEntry\x1a=\n\x0bRoutesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.routing.Route:\x02\x38\x01\"D\n\rTargetedRoute\x12\x14\n\x0ctarget_group\x18\x01 \x01(\x04\x12\x1d\n\x05route\x18\x02 \x01(\x0b\x32\x0e.routing.Route\"\xa8\x01\n\rUpdateMessage\x12\x15\n\rupdate_number\x18\x01 \x01(\x04\x12\x13\n\x0bsource_node\x18\x02 \x01(\x04\x12.\n\x0croute_update\x18\x03 \x01(\x0b\x32\x16.routing.TargetedRouteH\x00\x12\x31\n\x12route_table_update\x18\x04 \x01(\x0b\x32\x13.routing.RouteTableH\x00\x42\x08\n\x06updateb\x06proto3'
)




_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='routing.Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='next_hop', full_name='routing.Route.next_hop', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metric', full_name='routing.Route.metric', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=67,
)


_ROUTETABLE_ROUTESENTRY = _descriptor.Descriptor(
  name='RoutesEntry',
  full_name='routing.RouteTable.RoutesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='routing.RouteTable.RoutesEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='routing.RouteTable.RoutesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=193,
)

_ROUTETABLE = _descriptor.Descriptor(
  name='RouteTable',
  full_name='routing.RouteTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='routes', full_name='routing.RouteTable.routes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ROUTETABLE_ROUTESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=193,
)


_TARGETEDROUTE = _descriptor.Descriptor(
  name='TargetedRoute',
  full_name='routing.TargetedRoute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_group', full_name='routing.TargetedRoute.target_group', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route', full_name='routing.TargetedRoute.route', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=263,
)


_UPDATEMESSAGE = _descriptor.Descriptor(
  name='UpdateMessage',
  full_name='routing.UpdateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='update_number', full_name='routing.UpdateMessage.update_number', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_node', full_name='routing.UpdateMessage.source_node', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route_update', full_name='routing.UpdateMessage.route_update', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route_table_update', full_name='routing.UpdateMessage.route_table_update', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='update', full_name='routing.UpdateMessage.update',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=266,
  serialized_end=434,
)

_ROUTETABLE_ROUTESENTRY.fields_by_name['value'].message_type = _ROUTE
_ROUTETABLE_ROUTESENTRY.containing_type = _ROUTETABLE
_ROUTETABLE.fields_by_name['routes'].message_type = _ROUTETABLE_ROUTESENTRY
_TARGETEDROUTE.fields_by_name['route'].message_type = _ROUTE
_UPDATEMESSAGE.fields_by_name['route_update'].message_type = _TARGETEDROUTE
_UPDATEMESSAGE.fields_by_name['route_table_update'].message_type = _ROUTETABLE
_UPDATEMESSAGE.oneofs_by_name['update'].fields.append(
  _UPDATEMESSAGE.fields_by_name['route_update'])
_UPDATEMESSAGE.fields_by_name['route_update'].containing_oneof = _UPDATEMESSAGE.oneofs_by_name['update']
_UPDATEMESSAGE.oneofs_by_name['update'].fields.append(
  _UPDATEMESSAGE.fields_by_name['route_table_update'])
_UPDATEMESSAGE.fields_by_name['route_table_update'].containing_oneof = _UPDATEMESSAGE.oneofs_by_name['update']
DESCRIPTOR.message_types_by_name['Route'] = _ROUTE
DESCRIPTOR.message_types_by_name['RouteTable'] = _ROUTETABLE
DESCRIPTOR.message_types_by_name['TargetedRoute'] = _TARGETEDROUTE
DESCRIPTOR.message_types_by_name['UpdateMessage'] = _UPDATEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), {
  'DESCRIPTOR' : _ROUTE,
  '__module__' : 'routing_pb2'
  # @@protoc_insertion_point(class_scope:routing.Route)
  })
_sym_db.RegisterMessage(Route)

RouteTable = _reflection.GeneratedProtocolMessageType('RouteTable', (_message.Message,), {

  'RoutesEntry' : _reflection.GeneratedProtocolMessageType('RoutesEntry', (_message.Message,), {
    'DESCRIPTOR' : _ROUTETABLE_ROUTESENTRY,
    '__module__' : 'routing_pb2'
    # @@protoc_insertion_point(class_scope:routing.RouteTable.RoutesEntry)
    })
  ,
  'DESCRIPTOR' : _ROUTETABLE,
  '__module__' : 'routing_pb2'
  # @@protoc_insertion_point(class_scope:routing.RouteTable)
  })
_sym_db.RegisterMessage(RouteTable)
_sym_db.RegisterMessage(RouteTable.RoutesEntry)

TargetedRoute = _reflection.GeneratedProtocolMessageType('TargetedRoute', (_message.Message,), {
  'DESCRIPTOR' : _TARGETEDROUTE,
  '__module__' : 'routing_pb2'
  # @@protoc_insertion_point(class_scope:routing.TargetedRoute)
  })
_sym_db.RegisterMessage(TargetedRoute)

UpdateMessage = _reflection.GeneratedProtocolMessageType('UpdateMessage', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEMESSAGE,
  '__module__' : 'routing_pb2'
  # @@protoc_insertion_point(class_scope:routing.UpdateMessage)
  })
_sym_db.RegisterMessage(UpdateMessage)


_ROUTETABLE_ROUTESENTRY._options = None
# @@protoc_insertion_point(module_scope)
